### PR TITLE
feat: support large models (>2GB)

### PR DESCRIPTION
**Pull request by senysenyseny16**
Large models (>2GB) support.

https://github.com/onnx/onnx/blob/main/docs/ExternalData.md

### CODE REVIEW

**Comment by daquexian** [comment]
Hi :)

I tried this PR but still got an "larger than 2gb" exception in onnx optimizer. Do you have any ideas?

**Comment by senysenyseny16** [comment]
Hi, @daquexian 

It is because `onnxoptimizer` doesn't support large models:

```python
File "onnx-simplifier/onnxsim/onnx_simplifier.py", line 329, in optimize
    model = onnxoptimizer.optimize(model, optimizers_list,
File "venv/lib/python3.9/site-packages/onnxoptimizer/__init__.py", line 46, in optimize
    model_str = model.SerializeToString()
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 2954536134
```
I hope to send a patch to `onnxoptimizer` as soon as possible.

**Comment by daquexian** [comment]
> Hi, @daquexian
> 
> It is because `onnxoptimizer` doesn't support large models:
> 
> ```python
> File "onnx-simplifier/onnxsim/onnx_simplifier.py", line 329, in optimize
>     model = onnxoptimizer.optimize(model, optimizers_list,
> File "venv/lib/python3.9/site-packages/onnxoptimizer/__init__.py", line 46, in optimize
>     model_str = model.SerializeToString()
> ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 2954536134
> ```
> 
> I hope to send a patch to `onnxoptimizer` as soon as possible.

Are you already familiar with onnxoptimizer? If not it will be better to wait for me to fix it 😉

**Comment by daquexian** [comment]
onnxsim supports large model now, so I'm closing this PR. Thanks for your contribution!

**Pull request closed without merging**
