### PR TITLE
simplify can skip custom ops

### PR DESCRIPTION
**Pull request by FRAOTIAC**
Add optional custom op list that can be skiped during simplify

### CODE REVIEW

**Comment by minrui-hust** [comment]
great feature, why not merge?

**Comment by tigert1998** [comment]
great feature, why not merge?

**Comment by tigert1998** [comment]
I think the meaning of this PR is: when there is a custom operator without implementation, the simplifier can treat the output tensor as a non-constant tensor and continue the constant-folding process as far as possible.

**Comment by daquexian** [comment]
> I think the meaning of this PR is: when there is a custom operator without implementation, the simplifier can treat the output tensor as a non-constant tensor and continue the constant-folding process as far as possible.

Have you tried this pr on your side? I'm afraid this pr doesn't work as what you expected

**Comment by tigert1998** [comment]
I haven't tried. But I need a similar one.

**Comment by daquexian** [comment]
Latest onnxsim skips custom op automatically. Thanks for your contribution!

**Pull request closed without merging**
