### PR TITLE
VERSION file

### PR DESCRIPTION
**Pull request by CristiFati**
Using versioning system to automatically get the version and then using the *create\_version* command is nice, but it breaks the case when the package is (built and) installed from source (I encountered it on *aarch64* - where there's no prebuilt *.whl*), as there's no repository and the command fails. Details: [[GitHub]: daquexian/onnx-simplifier - remove file VERSION_NUMBER, register executor in init.py (@CristiFati's comment)](https://github.com/daquexian/onnx-simplifier/commit/6a24b804140815913bb3203c917f5ab84e0cec64#commitcomment-90226433).

Added the file and used it only as a fallback (for the aforementioned scenario).

The drawback is that it will have to be updated with each (public) release.

Note: My 1<sup>st</sup> attempt was to use a *ReggaExp* on the parent folder name (as it is in the archive), but that didn't work, as *PIP* unpacks it into a temporary.

### CODE REVIEW

**Comment by daquexian** [comment]
Thanks! I'll check it in these days.

**Comment by CristiFati** [comment]
@daquexian: First please approve the workflows run, so tests can be run.

**Comment by CristiFati** [comment]
Thank you. Unfortunately, I forgot something crucial and build failed. I fixed it but apparently the approval is required for every additional commit.

**Comment by daquexian** [comment]
Thanks for your contribution and sorry for the late response. It looks good to me.

**Pull request merged**
